spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.appication.name}
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json:
          trusted.packages: com.codingshuttle.linkedin.*